version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: finance-postgres
    environment:
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass123
      POSTGRES_DB: financedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: